# Generated by Django 5.0.1 on 2024-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(default='null'),
        ),
    ]
